services:
  - type: web
    name: job-portal-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build:linux
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
